name: Docker Image CI

on:
  push:
    paths:
      - 'release-versions/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag go2tom42/megatv:latest
      - name: Push the latest Docker image
        run: docker push tom42/megatv:latest
