name: Get latest release version
on:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/xteve-project/xTeVe/releases/latest | \
          jq -r ".tag_name" > release-versions/xteve-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git add release-versions/xteve-latest.txt
          git config --global user.name 'go2tom42'
          git config --global user.email 'go2tom42@users.noreply.github.com'
          git commit -am "New release version"
          git push
